// @generated by `cargo xtask apps sync --locked`; source of truth is
// apps/mfg/source.lock.toml. This is a build-time package input, never a
// runtime remote import.
export const cowdAppSources = [
  {
    appId: "mfg",
    git: "https://gitee.com/eyeout/cowd-app-mfg",
    rev: "2d056c833d1d20a6c9723d70a9766ec605d78018",
    package: "@cowd/app-mfg-webui",
  },
] as const;
