// @generated by `cargo xtask apps sync --locked`; source of truth is apps/catalog.toml.
// These are build-time package inputs, never runtime remote imports.
export const cowdAppSources = [
  {
    appId: "mfg",
    git: "https://gitee.com/eyeout/cowd-app-mfg",
    rev: "272227bfc9d09e821dded89e1800e332c2366e46",
    package: "@cowd/app-mfg-webui",
  },
] as const;
