// @generated by `cargo xtask apps sync --locked`; source of truth is apps/catalog.toml.
// These are build-time package inputs, never runtime remote imports.
export const cowdAppSources = [
  {
    appId: "mfg",
    git: "https://gitee.com/eyeout/cowd-app-mfg",
    rev: "b0f849eb40beec1355a3309e4a12a2ea981d7664",
    package: "@cowd/app-mfg-webui",
  },
] as const;
