[package]
name = "cowd-app-mfg"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
matrix = { path = "../matrix" }
matrix-store = { path = "../matrix-store" }
rusqlite = { version = "0.31", features = ["bundled"] }
serde.workspace = true
serde_json.workspace = true
thiserror = "2"
uuid.workspace = true

[lib]
name = "app_mfg"

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "allow", priority = -2 }
