[package]
name = "connector-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
connector = { path = "../connector" }
postgres = "0.19"
storage = { path = "../storage", features = ["storage-postgres"] }

[lints]
workspace = true
