// @generated by `cargo xtask apps sync --locked`; source of truth is apps/catalog.toml.
// Each entry is a compile-time linked product bundle, never a runtime import.

use cowd_app_host::StaticAppProduct;

#[must_use]
pub fn compiled_products() -> Vec<StaticAppProduct> {
    vec![
        #[cfg(feature = "app-mfg")]
        cowd_app_mfg_bundle::product().with_source_lock(cowd_app_host::StaticAppSourceLock::new(
            "https://gitee.com/eyeout/cowd-app-mfg",
            "d615f768c5eda722f12ebce7c4e53781cf536103",
        )),
    ]
}
