// @generated by `cargo xtask apps sync --locked`; source of truth is apps/catalog.toml.
// Each entry is a compile-time linked product bundle, never a runtime import.

use cowd_app_host::StaticAppProduct;

#[must_use]
pub fn compiled_products() -> Vec<StaticAppProduct> {
    vec![
        #[cfg(feature = "app-mfg")]
        cowd_app_mfg_bundle::product().with_source_lock(cowd_app_host::StaticAppSourceLock::new(
            "https://gitee.com/eyeout/cowd-app-mfg",
            "616566d969dc6ba2385605ea91cb231aee0b7510",
        )),
    ]
}
